### ISSUE TITLE
Publish failed

### ISSUE THREAD

**Issue by doubleJazzCat** [eidam/cf-workers-status-page#159]
```
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 Built successfully, built project size is 42 KiB.
 Created namespace for Workers Site "__cf-workers-status-page-production-workers_sites_assets"
 成功
 Uploading site files
Error:  Error: error decoding response body: invalid type: map, expected unit at line 2 column 12
```

**Comment by doubleJazzCat** [comment]
```
$ node ./src/cli/gcMonitors.js
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /github/workspace/src/cli/gcMonitors.js:67:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Done in 0.47s.
```

**Comment by 123hi123** [comment]
Same

**Comment by naodeng** [comment]
Same

**Comment by FrankWkd-Pro** [comment]
Same+1

**Comment by naodeng** [comment]
I replaced it with a new project: https://github.com/naodeng/cf-workers-status-page, and it’s working well. The website is: https://status.inaodeng.com/.
