### ISSUE TITLE
TypeError for src/cli/gcMonitors @ Publish stage of deploy

### ISSUE THREAD

**Issue by DieselGaming** [eidam/cf-workers-status-page#37]
```
$ node ./src/cli/gcMonitors.js
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /github/workspace/src/cli/gcMonitors.js:67:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

![image](https://user-images.githubusercontent.com/44411085/117369172-741bdd80-aebc-11eb-9527-594ec6638fe2.png)

Line 67:
![image](https://user-images.githubusercontent.com/44411085/117369277-9f063180-aebc-11eb-91d8-af24db679c3c.png)

Doesn't actually upload to workers, left with the default template from Cloudflare.

**Comment by DieselGaming** [comment]
Well, actually it appears the webhooks are working? Yet going to the actual URL still returns the data from the template.
![image](https://user-images.githubusercontent.com/44411085/117369607-09b76d00-aebd-11eb-8325-11cad70720be.png)

**Comment by eidam** [comment]
> Well, actually it appears the webhooks are working? Yet going to the actual URL still returns the data from the template.
> ![image](https://user-images.githubusercontent.com/44411085/117369607-09b76d00-aebd-11eb-8325-11cad70720be.png)

What template do you mean? The new Workers one?

**Comment by eidam** [comment]
The last step of deployment should not affect upload of the Workers code. Do you mind sharing the forked repository/failed GitHub actions link?

**Comment by DieselGaming** [comment]
> What template do you mean? The new Workers one?
Yes, the worker's Quick Edit shows the default file & going to the URL returns its data.

> The last step of deployment should not affect upload of the Workers code. Do you mind sharing the forked repository/failed GitHub actions link?

OH, I didn't realise that it actually created a new worker under the `name` value in `wrangler.toml` (which was different by a single character - why I didn't spot it) and that it added `-production` to the URL as well. Everything seems to be working, thank you!

**Comment by eidam** [comment]
Happy to hear it works! I will def take a look at the error, it's confusing at least. :)

**Comment by DieselGaming** [comment]
Thanks!

The next thing is that I added another monitor - it was added to the status page, then I removed it from the config. However, it doesn't show up anymore, but its results are still counted in the KV and on the webpage. If that monitor goes offline, it will say that not all systems are online, yet the 3 other monitors all show green, there isn't a non-operational one. Any ideas?
Oh, and when I removed the monitor from the config, it was still present in the KV storage.

**Comment by DieselGaming** [comment]
> However, it doesn't show up anymore

Oh my god, forget this as well - it literally just appeared.

Forgive my stupidity :)

I'll leave this open for the time being.

**Comment by eidam** [comment]
The gcMonitors script should take care of cleaning up the state, seems like this part is broken. 

> Oh, and when I removed the monitor from the config, it was still present in the KV storage.
That is because KV storage is eventually consistent, your changes are being re-pushed by the CRON trigger. Your changes take up to 1 minute to propagate, however, the CRON trigger reads/writes the state every minute from a different location, so it will most probably be just rewriting your state. 

If you want to manually fix the state, pause your CRON trigger, update the state, wait a couple of minutes, and then reenable the CRON trigger. :)
