### ISSUE TITLE
First time load, not working

### ISSUE THREAD

**Issue by PadowYT2** [eidam/cf-workers-status-page#63]
I'm trying to run this for the first time and this is what I get, any help would be great
`(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 29965 files and directories currently installed.)
Preparing to unpack .../libonig4_6.1.3-2+deb9u2_amd64.deb ...
Unpacking libonig4:amd64 (6.1.3-2+deb9u2) ...
Selecting previously unselected package libjq1:amd64.
Preparing to unpack .../libjq1_1.5+dfsg-1.3_amd64.deb ...
Unpacking libjq1:amd64 (1.5+dfsg-1.3) ...
Selecting previously unselected package jq.
Preparing to unpack .../jq_1.5+dfsg-1.3_amd64.deb ...
Unpacking jq (1.5+dfsg-1.3) ...
Setting up libonig4:amd64 (6.1.3-2+deb9u2) ...
Setting up libjq1:amd64 (1.5+dfsg-1.3) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up jq (1.5+dfsg-1.3) ...
Secret SECRET_SLACK_WEBHOOK_URL not set, creating dummy one...
Secret SECRET_TELEGRAM_API_TOKEN not set, creating dummy one...
Secret SECRET_TELEGRAM_CHAT_ID not set, creating dummy one...
Secret SECRET_DISCORD_WEBHOOK_URL not set, creating dummy one...
  Installing wranglerjs v1.19.2...
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN wrangler-js@0.1.11 No description
npm WARN wrangler-js@0.1.11 No repository field.

added 343 packages from 201 contributors and audited 345 packages in 6.67s

8 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
(node:325) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/github/workspace/out/_flareact/static/build-manifest.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/github/workspace/node_modules/flareact/configs/webpack.worker.config.js:19:8)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/github/workspace/node_modules/flareact/webpack.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
(node:325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:325) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Oops! Wrangler encountered an error:

panicked at 'could not parse wranglerjs output: Error("EOF while parsing a value", line: 1, column: 0)', src/wranglerjs/mod.rs:50:43

Please help Cloudflare debug this issue by submitting the error report
(/github/workspace/errors/1630693934729.log)

To submit this error report to Cloudflare, run:

    $ wrangler report
        
Enter the secret text you'd like assigned to the variable SECRET_SLACK_WEBHOOK_URL on the script named cf-workers-status-page-production:
 Creating the secret for script name cf-workers-status-page-production
 Worker cf-workers-status-page-production doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
Error: No such file or directory (os error 2)`

**Comment by PadowYT2** [comment]
nvm, im dumb
